<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('token_usage_logs', function (Blueprint $table) {
            $table->unsignedInteger('input_tokens')->nullable()->after('tokens_used')
                ->comment('Prompt / context tokens sent to the LLM');
            $table->unsignedInteger('output_tokens')->nullable()->after('input_tokens')
                ->comment('Completion tokens generated by the LLM');
        });
    }

    public function down(): void
    {
        Schema::table('token_usage_logs', function (Blueprint $table) {
            $table->dropColumn(['input_tokens', 'output_tokens']);
        });
    }
};
